//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DB_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Number { get; set; }
        public string BIC { get; set; }
        public int ID { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Contragent Contragent { get; set; }
    }
}
