//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DB_First
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerShopEntities : DbContext
    {
        public ComputerShopEntities()
            : base("name=ComputerShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Contragent> Contragent { get; set; }
        public virtual DbSet<Features> Features { get; set; }
        public virtual DbSet<FeatureValues> FeatureValues { get; set; }
        public virtual DbSet<Nomeklatura> Nomeklatura { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<SerialNumbers> SerialNumbers { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<SupplyNomenklatura> SupplyNomenklatura { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
