//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DB_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.SupplyNomenklatura = new HashSet<SupplyNomenklatura>();
        }
    
        public string Number { get; set; }
        public System.DateTime SupplyDate { get; set; }
        public decimal TotalSum { get; set; }
        public int ID { get; set; }
        public int ShopNumber { get; set; }
        public string TabNumber { get; set; }
    
        public virtual Contragent Contragent { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyNomenklatura> SupplyNomenklatura { get; set; }
    }
}
